---
engines:
  csslint:
    enabled: false
  eslint:
    enabled: true
    channel: "eslint-2"
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths:
- src/public/**/*
- locales/**/*
- build/**/*
