---
engines:
  csslint:
    enabled: false
  eslint:
    enabled: true
    channel: "eslint-2"
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.jsx"
exclude_paths:
- config/**/*
- public/**/*
- locales/**/*
