sudo: false
env:
  - CXX=g++-4.8
language: "node_js"
node_js:
  - "10.3.0"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - graphicsmagick
cache:
  directories:
    - node_modules
